import { CheckCircle2 } from "lucide-react";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import PageHero from "@/components/PageHero";
import Team from "@/components/Team";
import CTA from "@/components/CTA";
import { company, companyProfile, differentiators } from "@/lib/public-content";
export default function AboutPage() { return <main className="min-h-screen pt-20"><Navbar /><PageHero eyebrow={`About ${company.name}`} title="Technology shaped around real business needs" description="A Ghana-based digital team helping businesses turn ideas, customer needs and operational challenges into useful digital products." image="/images/photos/about-workshop.webp" imageAlt="Professionals collaborating in a workshop" action={{label:"How we work",href:"/process"}} />
<section className="bg-white py-16 sm:py-20"><div className="section-shell grid gap-10 lg:grid-cols-[1.1fr_0.9fr] lg:gap-16"><div><p className="eyebrow mb-4">Our story</p><h2 className="section-heading">Digital work should feel clear and purposeful.</h2><div className="mt-6 space-y-5 text-lg leading-relaxed text-slate-600">{companyProfile.story.map(paragraph=><p key={paragraph}>{paragraph}</p>)}</div></div><div className="grid gap-4"><article className="rounded-[1.5rem] bg-[#edf1eb] p-7"><p className="eyebrow mb-3">Our mission</p><p className="leading-relaxed text-slate-800">{companyProfile.mission}</p></article><article className="rounded-[1.5rem] bg-[#285749] p-7 text-white"><p className="mb-3 text-xs font-bold uppercase tracking-widest text-[#d4e9d8]">Our vision</p><p className="leading-relaxed">{companyProfile.vision}</p></article></div></div></section>
<section className="bg-[#f5f3ed] py-16 sm:py-20"><div className="section-shell"><p className="eyebrow mb-4">How we work</p><h2 className="section-heading mb-9">Values we can be measured by.</h2><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{companyProfile.values.map(([title,description])=><article key={title} className="rounded-[1.4rem] border border-slate-200 bg-white p-6"><CheckCircle2 aria-hidden="true" className="mb-6 h-6 w-6 text-[#285749]" /><h3 className="text-lg font-bold text-slate-900">{title}</h3><p className="mt-2 text-sm leading-relaxed text-slate-600">{description}</p></article>)}</div></div></section>
<section className="bg-white py-16 sm:py-20"><div className="section-shell"><p className="eyebrow mb-4">Why UNIFOTEC-WEB</p><h2 className="section-heading mb-9">Fast-moving work without losing clarity.</h2><div className="grid gap-4 md:grid-cols-2">{differentiators.map(([title,description],index)=><article key={title} className="flex gap-5 rounded-[1.4rem] border border-slate-200 p-6"><span className="font-black text-[#285749]">{String(index+1).padStart(2,"0")}</span><div><h3 className="text-lg font-bold text-slate-900">{title}</h3><p className="mt-2 leading-relaxed text-slate-600">{description}</p></div></article>)}</div></div></section><Team /><CTA /><Footer /></main>; }
